# Generated by Django 4.0.3 on 2022-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='photo',
            name='classification',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
