# Generated by Django 4.0.3 on 2022-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_delete_images_photo_classification_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='classification',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
