# Generated by Django 4.0.1 on 2022-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0005_remove_photo_classification_remove_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='classification',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
